Task 2
sergey-berezin/s02170093 pull request #3
Opened 2020-10-18 23:41 UTC by andredolbnin

2020-10-19 08:15 UTC, sergey-berezin requested changes

2020-10-19 08:15 UTC, sergey-berezin commented on RecognitionApp/MainWindow.xaml.cs
> +            ImgInf img = ImgCollection.First(i => i.Path == pr.Path);
Может конкурентно вызываться из разных потоков. Используйте Dispatcher.BeginInvoke.

2020-10-19 08:15 UTC, sergey-berezin commented on RecognitionApp/MainWindow.xaml.cs
> +    public class ObsOneLabelCollection : ObservableCollection<OneLabel> { }
Такое наследование не имеет смысла (только для использование имени в Xaml)

2020-10-19 08:15 UTC, sergey-berezin commented on RecognitionApp/MainWindow.xaml.cs
> +            ImgCollection = FindResource("key_OIC") as ObsImgCollection;
Лучше предоставлять объекты, созданные в MainWindow для привязки в Xaml.

2020-10-19 22:59 UTC, andredolbnin commented
Здравствуйте!
Исправил эти ошибки.

2020-10-26 08:58 UTC, sergey-berezin commented on RecognitionApp/MainWindow.xaml.cs
> +            LbOIC.SetBinding(ItemsControl.ItemsSourceProperty, BndImgColl);
Так тоже работает, но этот путь сложнее и многословнее чем определить public свойство и сделать привязку к нему в XAML. 

Задание принимаю, но далее рассматривайте в первую очередь описание привязок в XAML.

2020-10-26 08:58 UTC, sergey-berezin approved these changes

2020-10-26 08:58 UTC, merged